[package]
name = "battleship"
version = "0.1.0"
authors = [
    "Dennis Altenhoff <daltenhoff@uos.de> ",
    " Tim Bohne <tbohne@uos.de> ",
    " Svantje Jung <svjung@uos.de> ",
    " Famke Lamberti <flamberti@uos.de> "
]

[dependencies]
clap = "2.20"
term-painter = "0.2"
rand = "0.3.15"
